// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDkruplszZ3Tio0TUuZ7lXtGWaK4ULeHU',
    appId: '1:792585921183:web:f3f1cc9759ed07344678aa',
    messagingSenderId: '792585921183',
    projectId: 'healthmate-project',
    authDomain: 'healthmate-project.firebaseapp.com',
    storageBucket: 'healthmate-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8k-UcHf7gqvjKHqqNLAVakpUc6S3eWJE',
    appId: '1:792585921183:android:d15bb2be4204a8ce4678aa',
    messagingSenderId: '792585921183',
    projectId: 'healthmate-project',
    storageBucket: 'healthmate-project.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDkruplszZ3Tio0TUuZ7lXtGWaK4ULeHU',
    appId: '1:792585921183:web:70264388b34ca8104678aa',
    messagingSenderId: '792585921183',
    projectId: 'healthmate-project',
    authDomain: 'healthmate-project.firebaseapp.com',
    storageBucket: 'healthmate-project.appspot.com',
  );
}
